// ============================================================
// LAWTALK — MOCK DATA (Seeded Lawyers)
// ============================================================
// This file provides seed data for the frontend demo.
// Backend dev: Replace this with API calls to GET /api/lawyers
// Endpoints needed:
//   GET  /api/lawyers           — paginated list with filters
//   GET  /api/lawyers/:id       — single lawyer profile
//   POST /api/lawyers/register  — lawyer onboarding
//   PUT  /api/lawyers/:id/verify — admin verification
// ============================================================

import { LAWYER_STATUS } from "./constants";

export const MOCK_LAWYERS = [
  {
    id: "lawyer_001",
    name: "Adv. Priya Sharma",
    phone: "9876543210",
    email: "priya.sharma@lawtalk.in",
    city: "Delhi",
    state: "Delhi",
    experience: 12,
    specializations: ["Family Law", "Divorce & Matrimonial"],
    languages: ["English", "Hindi"],
    pricePerMinute: 45,
    bio: "Senior family law advocate with 12 years of experience handling divorce, custody, and matrimonial disputes. Empathetic listener with a strong record in mediation.",
    barCouncilId: "D/1234/2012",
    rating: 4.8,
    reviewCount: 342,
    totalConsultations: 1250,
    isOnline: true,
    status: LAWYER_STATUS.VERIFIED,
    avatar: null,
    education: "LLB — Delhi University (2012)",
    documents: { marksheet: null, barCertificate: null, idProof: null },
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "lawyer_002",
    name: "Adv. Rajesh Verma",
    phone: "9812345678",
    email: "rajesh.verma@lawtalk.in",
    city: "Mumbai",
    state: "Maharashtra",
    experience: 8,
    specializations: ["Criminal Law", "Civil Law"],
    languages: ["English", "Hindi", "Marathi"],
    pricePerMinute: 60,
    bio: "Experienced criminal defense lawyer with expertise in bail applications, FIR quashing, and trial proceedings. High Court panel advocate.",
    barCouncilId: "M/5678/2016",
    rating: 4.6,
    reviewCount: 218,
    totalConsultations: 890,
    isOnline: false,
    status: LAWYER_STATUS.VERIFIED,
    avatar: null,
    education: "LLM — Mumbai University (2016)",
    documents: { marksheet: null, barCertificate: null, idProof: null },
    createdAt: "2024-02-20T10:00:00Z",
  },
  {
    id: "lawyer_003",
    name: "Adv. Meena Krishnan",
    phone: "9944332211",
    email: "meena.k@lawtalk.in",
    city: "Chennai",
    state: "Tamil Nadu",
    experience: 15,
    specializations: ["Property Law", "Civil Law", "Consumer Law"],
    languages: ["English", "Tamil"],
    pricePerMinute: 55,
    bio: "Veteran property law expert with 15 years in real estate disputes, title verification, and RERA matters. Fluent in both English and Tamil legal proceedings.",
    barCouncilId: "TN/9012/2010",
    rating: 4.9,
    reviewCount: 567,
    totalConsultations: 2100,
    isOnline: true,
    status: LAWYER_STATUS.VERIFIED,
    avatar: null,
    education: "LLB — Madras Law College (2010)",
    documents: { marksheet: null, barCertificate: null, idProof: null },
    createdAt: "2024-01-01T10:00:00Z",
  },
  {
    id: "lawyer_004",
    name: "Adv. Arjun Mehta",
    phone: "9930112233",
    email: "arjun.mehta@lawtalk.in",
    city: "Ahmedabad",
    state: "Gujarat",
    experience: 5,
    specializations: ["Corporate Law", "Tax Law"],
    languages: ["English", "Hindi", "Gujarati"],
    pricePerMinute: 30,
    bio: "Young corporate lawyer specializing in startup legal compliance, GST matters, and corporate governance. IBA member with global exposure.",
    barCouncilId: "GJ/3456/2019",
    rating: 4.4,
    reviewCount: 98,
    totalConsultations: 340,
    isOnline: true,
    status: LAWYER_STATUS.VERIFIED,
    avatar: null,
    education: "LLB — Gujarat National Law University (2019)",
    documents: { marksheet: null, barCertificate: null, idProof: null },
    createdAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "lawyer_005",
    name: "Adv. Sunita Rao",
    phone: "9866554433",
    email: "sunita.rao@lawtalk.in",
    city: "Hyderabad",
    state: "Telangana",
    experience: 10,
    specializations: ["Labour Law", "Civil Law", "Consumer Law"],
    languages: ["English", "Telugu", "Hindi"],
    pricePerMinute: 40,
    bio: "Labour law specialist with extensive experience in employment disputes, wrongful termination, and POSH Act cases. Strong track record with major IT companies.",
    barCouncilId: "TS/7890/2014",
    rating: 4.7,
    reviewCount: 289,
    totalConsultations: 1100,
    isOnline: false,
    status: LAWYER_STATUS.VERIFIED,
    avatar: null,
    education: "LLB — NALSAR University of Law (2014)",
    documents: { marksheet: null, barCertificate: null, idProof: null },
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "lawyer_006",
    name: "Adv. Karan Singh",
    phone: "9814567890",
    email: "karan.singh@lawtalk.in",
    city: "Chandigarh",
    state: "Punjab",
    experience: 7,
    specializations: ["NRI Legal Services", "Property Law", "Immigration Law"],
    languages: ["English", "Hindi", "Punjabi"],
    pricePerMinute: 50,
    bio: "NRI law specialist helping overseas Indians with property disputes, OCI matters, and inheritance cases. Extensive experience with Punjab & Haryana High Court.",
    barCouncilId: "PB/2345/2017",
    rating: 4.5,
    reviewCount: 176,
    totalConsultations: 680,
    isOnline: true,
    status: LAWYER_STATUS.VERIFIED,
    avatar: null,
    education: "LLB — Panjab University (2017)",
    documents: { marksheet: null, barCertificate: null, idProof: null },
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "lawyer_007",
    name: "Adv. Nisha Desai",
    phone: "9823456789",
    email: "nisha.desai@lawtalk.in",
    city: "Pune",
    state: "Maharashtra",
    experience: 3,
    specializations: ["Cyber Law", "Intellectual Property"],
    languages: ["English", "Marathi", "Hindi"],
    pricePerMinute: 25,
    bio: "Emerging cyber law and IP attorney with specialization in data privacy, copyright infringement, and tech startup IP protection. Up-to-date with IT Act amendments.",
    barCouncilId: "M/6789/2021",
    rating: 4.3,
    reviewCount: 54,
    totalConsultations: 180,
    isOnline: true,
    status: LAWYER_STATUS.VERIFIED,
    avatar: null,
    education: "LLB — Symbiosis Law School (2021)",
    documents: { marksheet: null, barCertificate: null, idProof: null },
    createdAt: "2024-04-05T10:00:00Z",
  },
  {
    id: "lawyer_008",
    name: "Adv. Mohammed Ali Khan",
    phone: "9887766554",
    email: "ali.khan@lawtalk.in",
    city: "Lucknow",
    state: "Uttar Pradesh",
    experience: 20,
    specializations: ["Constitutional Law", "Criminal Law"],
    languages: ["English", "Hindi", "Urdu"],
    pricePerMinute: 80,
    bio: "Senior constitutional law practitioner with 2 decades of experience including cases before the Supreme Court of India. Expertise in writ petitions, PIL, and fundamental rights cases.",
    barCouncilId: "UP/1111/2005",
    rating: 4.9,
    reviewCount: 892,
    totalConsultations: 3200,
    isOnline: false,
    status: LAWYER_STATUS.VERIFIED,
    avatar: null,
    education: "LLM — Allahabad University (2005)",
    documents: { marksheet: null, barCertificate: null, idProof: null },
    createdAt: "2024-01-05T10:00:00Z",
  },
];

// Pending lawyer registrations (awaiting admin verification)
export const MOCK_PENDING_LAWYERS = [
  {
    id: "pending_001",
    name: "Adv. Rohit Gupta",
    phone: "9999888877",
    email: "rohit.gupta@example.com",
    city: "Jaipur",
    state: "Rajasthan",
    experience: 4,
    specializations: ["Debt Recovery", "Civil Law"],
    languages: ["English", "Hindi"],
    pricePerMinute: 20,
    bio: "Debt recovery and civil litigation specialist based in Jaipur. Handled 100+ DRT cases.",
    barCouncilId: "RJ/4567/2020",
    rating: 0,
    reviewCount: 0,
    totalConsultations: 0,
    isOnline: false,
    status: LAWYER_STATUS.PENDING,
    avatar: null,
    education: "LLB — University of Rajasthan (2020)",
    documents: { marksheet: null, barCertificate: null, idProof: null },
    createdAt: new Date().toISOString(),
  },
];
